///////////////////////////////////////////////////////////////////////////////
// Dependencies
///////////////////////////////////////////////////////////////////////////////
#include <Engine/Core.hpp>
#include <fstream>
#include <iomanip>
#include <vector>
#include <zlib.h>

///////////////////////////////////////////////////////////////////////////////
// Namespace tkd
///////////////////////////////////////////////////////////////////////////////
namespace tkd
{

///////////////////////////////////////////////////////////////////////////////
bool FileToHeader(
    const FilePath& filePath,
    const FilePath& headerPath,
    const FString& arrayName
)
{
    std::cout << "Converting file: " << filePath
              << " to header: " << headerPath << std::endl;

    // Open input file in binary mode
    std::ifstream inputFile(
        filePath.c_str(), std::ios::binary | std::ios::ate
    );
    if (!inputFile.is_open())
    {
        std::cerr << "Error: Cannot open input file: " << filePath
                  << std::endl;
        return false;
    }

    std::cout << "Processing file data..." << std::endl;

    // Get file size
    std::streamsize fileSize = inputFile.tellg();
    inputFile.seekg(0, std::ios::beg);

    std::cout << "Original file size: " << fileSize << " bytes" << std::endl;

    std::cout << "Reading file..." << std::endl;

    // Read file contents
    std::vector<uint8_t> buffer(fileSize);
    if (!inputFile.read(reinterpret_cast<char*>(buffer.data()), fileSize))
    {
        std::cerr << "Error: Failed to read input file: " << filePath
                  << std::endl;
        inputFile.close();
        return false;
    }
    inputFile.close();

    std::cout << "Compressing data..." << std::endl;

    uLongf compressedSize = compressBound(fileSize);
    std::vector<uint8_t> compressedBuffer(compressedSize);

    int result = compress2(
        compressedBuffer.data(),
        &compressedSize,
        buffer.data(),
        fileSize,
        Z_BEST_COMPRESSION
    );

    if (result != Z_OK)
    {
        std::cerr << "Error: Compression failed with error code: " << result
                  << std::endl;
        return false;
    }

    std::cout << "Compression successful. Compressed size: " << compressedSize
              << " bytes" << std::endl;

    // Open output header file
    std::ofstream outputFile(headerPath.c_str());
    if (!outputFile.is_open())
    {
        std::cerr << "Error: Cannot create output file: " << headerPath
                  << std::endl;
        return false;
    }

    std::cout << "Writing header file..." << std::endl;

    // Generate header guard name
    std::string guardName = arrayName;
    for (char& c: guardName)
    {
        c = std::toupper(static_cast<unsigned char>(c));
    }
    guardName += "_H";

    // Write header file
    outputFile << "// Auto-generated header file from: " << filePath << "\n";
    outputFile << "// Generated byte array size: " << fileSize << " bytes\n\n";
    outputFile << "#ifndef " << guardName << "\n";
    outputFile << "#define " << guardName << "\n\n";
    outputFile << "#include <cstdint>\n\n";

    // Write array declaration
    outputFile << "const uint8_t " << arrayName << "[] = {\n";

    // Write byte data (16 bytes per line)
    const size_t bytesPerLine = 16;
    for (size_t i = 0; i < compressedBuffer.size(); ++i)
    {
        if (i % bytesPerLine == 0) { outputFile << "    "; }

        outputFile << "0x" << std::hex << std::setw(2) << std::setfill('0')
                   << static_cast<int>(compressedBuffer[i]);

        if (i < compressedBuffer.size() - 1)
        {
            outputFile << ",";
            if ((i + 1) % bytesPerLine == 0) { outputFile << "\n"; }
            else { outputFile << " "; }
        }
        else { outputFile << "\n"; }
    }

    outputFile << "};\n\n";
    outputFile << "const size_t " << arrayName << "Size = sizeof(" << arrayName
               << ");\n\n";
    outputFile << "#endif // " << guardName << "\n";

    outputFile.close();

    std::cout << "Header file written successfully: " << headerPath
              << std::endl;

    return true;
}

}   // namespace tkd

///////////////////////////////////////////////////////////////////////////////
int main(int argc, char* argv[])
{
    tkd::FArgs& args = tkd::FArgs::GetInstance();

    std::string inputFile;
    std::string outputFile;
    std::string arrayName = "fileData";

    args.AddFlags(
        "input", "Input file to convert to a C++ header", inputFile, true
    );
    args.AddFlags("output", "Output header file path", outputFile, true);
    args.AddFlags(
        "name", "Name of the generated byte array", arrayName, false
    );

    if (!args.Process(argc, argv)) { return args.GetExitCode(); }

    if (!tkd::FileToHeader(
            inputFile, outputFile, ("EMBEDDED_" + arrayName).c_str()
        ))
    {
        std::cerr << "Failed to convert file to header." << std::endl;
        return TKD_EXIT_FAILURE;
    }

    std::cout << "Successfully converted " << inputFile << " to " << outputFile
              << std::endl;

    return TKD_EXIT_SUCCESS;
}
