name: R-Type Release Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # TODO: Add steps to install dependencies

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    # TODO: Add steps to build the project


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    # TODO: Add steps to test the build artifacts
